/**
 * https://w3c.github.io/uievents-code/#code-value-tables
 */
import type { Layout } from '../../model';

export const workman: Layout = {
  default: {
    Backquote: { key: '`', type: 'symbol' },
    Digit1: { key: '1', type: 'digit' },
    Digit2: { key: '2', type: 'digit' },
    Digit3: { key: '3', type: 'digit' },
    Digit4: { key: '4', type: 'digit' },
    Digit5: { key: '5', type: 'digit' },
    Digit6: { key: '6', type: 'digit' },
    Digit7: { key: '7', type: 'digit' },
    Digit8: { key: '8', type: 'digit' },
    Digit9: { key: '9', type: 'digit' },
    Digit0: { key: '0', type: 'digit' },
    Minus: { key: '-', type: 'symbol' },
    Equal: { key: '=', type: 'symbol' },
    Backspace: { key: 'Backspace', type: 'sys' },
    Tab: { key: 'Tab', type: 'sys' },
    KeyQ: { key: 'q', type: 'letter' },
    KeyW: { key: 'd', type: 'letter' },
    KeyE: { key: 'r', type: 'letter' },
    KeyR: { key: 'w', type: 'letter' },
    KeyT: { key: 'b', type: 'letter' },
    KeyY: { key: 'j', type: 'letter' },
    KeyU: { key: 'f', type: 'letter' },
    KeyI: { key: 'u', type: 'letter' },
    KeyO: { key: 'p', type: 'letter' },
    KeyP: { key: ';', type: 'symbol' },
    BracketLeft: { key: '[', type: 'symbol' },
    BracketRight: { key: ']', type: 'symbol' },
    Backslash: { key: '\\', type: 'symbol', alternate: 'IntlBackslash' },
    CapsLock: { key: 'CapsLock', type: 'sys' },
    KeyA: { key: 'a', type: 'letter' },
    KeyS: { key: 's', type: 'letter' },
    KeyD: { key: 'h', type: 'letter' },
    KeyF: { key: 't', type: 'letter' },
    KeyG: { key: 'g', type: 'letter' },
    KeyH: { key: 'y', type: 'letter' },
    KeyJ: { key: 'n', type: 'letter' },
    KeyK: { key: 'e', type: 'letter' },
    KeyL: { key: 'o', type: 'letter' },
    Semicolon: { key: 'i', type: 'letter' },
    Quote: { key: "'", type: 'symbol' },
    Enter: { key: 'Enter', type: 'sys' },
    ShiftLeft: { key: 'Shift', type: 'sys' },
    IntlBackslash: { key: '\\', type: 'symbol', alternate: 'Backslash' },
    KeyZ: { key: 'z', type: 'letter' },
    KeyX: { key: 'x', type: 'letter' },
    KeyC: { key: 'm', type: 'letter' },
    KeyV: { key: 'c', type: 'letter' },
    KeyB: { key: 'v', type: 'letter' },
    KeyN: { key: 'k', type: 'letter' },
    KeyM: { key: 'l', type: 'letter' },
    Comma: { key: ',', type: 'symbol' },
    Period: { key: '.', type: 'symbol' },
    Slash: { key: '/', type: 'symbol' },
    ShiftRight: { key: 'Shift', type: 'sys' },
    ControlLeft: { key: 'Ctrl', type: 'sys' },
    Fn: {
      key: '',
      type: 'sys',
    },
    MetaLeft: { key: '', type: 'sys' },
    AltLeft: { key: 'Alt', type: 'sys' },
    Space: { key: '', type: 'sys' },
    AltRight: { key: 'Alt', type: 'sys' },
    MetaRight: { key: '', type: 'sys' },
    ContextMenu: { key: '', type: 'sys' },
    ControlRight: { key: 'Ctrl', type: 'sys' },
  },
  shift: {
    Backquote: { key: '~', type: 'symbol' },
    Digit1: { key: '!', type: 'symbol' },
    Digit2: { key: '@', type: 'symbol' },
    Digit3: { key: '#', type: 'symbol' },
    Digit4: { key: '$', type: 'symbol' },
    Digit5: { key: '%', type: 'symbol' },
    Digit6: { key: '^', type: 'symbol' },
    Digit7: { key: '&', type: 'symbol' },
    Digit8: { key: '*', type: 'symbol' },
    Digit9: { key: '(', type: 'symbol' },
    Digit0: { key: ')', type: 'symbol' },
    Minus: { key: '_', type: 'symbol' },
    Equal: { key: '+', type: 'symbol' },
    KeyQ: { key: 'Q', type: 'letter' },
    KeyW: { key: 'D', type: 'letter' },
    KeyE: { key: 'R', type: 'letter' },
    KeyR: { key: 'W', type: 'letter' },
    KeyT: { key: 'B', type: 'letter' },
    KeyY: { key: 'J', type: 'letter' },
    KeyU: { key: 'F', type: 'letter' },
    KeyI: { key: 'U', type: 'letter' },
    KeyO: { key: 'P', type: 'letter' },
    KeyP: { key: ':', type: 'symbol' },
    BracketLeft: { key: '{', type: 'symbol' },
    BracketRight: { key: '}', type: 'symbol' },
    Backslash: { key: '|', type: 'symbol', alternate: 'IntlBackslash' },
    KeyA: { key: 'A', type: 'letter' },
    KeyS: { key: 'S', type: 'letter' },
    KeyD: { key: 'H', type: 'letter' },
    KeyF: { key: 'T', type: 'letter' },
    KeyG: { key: 'G', type: 'letter' },
    KeyH: { key: 'Y', type: 'letter' },
    KeyJ: { key: 'N', type: 'letter' },
    KeyK: { key: 'E', type: 'letter' },
    KeyL: { key: 'O', type: 'letter' },
    Semicolon: { key: 'I', type: 'letter' },
    Quote: { key: '"', type: 'symbol' },
    IntlBackslash: { key: '|', type: 'symbol', alternate: 'Backslash' },
    KeyZ: { key: 'Z', type: 'letter' },
    KeyX: { key: 'X', type: 'letter' },
    KeyC: { key: 'M', type: 'letter' },
    KeyV: { key: 'C', type: 'letter' },
    KeyB: { key: 'V', type: 'letter' },
    KeyN: { key: 'K', type: 'letter' },
    KeyM: { key: 'L', type: 'letter' },
    Comma: { key: '<', type: 'symbol' },
    Period: { key: '>', type: 'symbol' },
    Slash: { key: '?', type: 'symbol' },
  },
};
